
R version 4.3.0 (2023-04-21) -- "Already Tomorrow"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(testthat)
> library(callr)
> 
> test_check("callr")
Error in dyn.unload(env$.path) : 
  shared object '/usr/local/lib/R/site-library/processx/libs//client.so' was not loaded
Calls: <Anonymous> -> <Anonymous> -> dyn.unload
Error in dyn.unload(env$.path) : 
  shared object '/usr/local/lib/R/site-library/processx/libs//client.so' was not loaded
Calls: <Anonymous> -> <Anonymous> -> dyn.unload
[ FAIL 11 | WARN 0 | SKIP 26 | PASS 261 ]

══ Skipped tests ═══════════════════════════════════════════════════════════════
• On CRAN (26)

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-error.R:3:3'): error is propagated, .Last.error is set ─────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'asciicast'
Backtrace:
    ▆
 1. ├─callr:::expect_r_process_snapshot(...) at test-error.R:3:2
 2. └─base::loadNamespace(x) at callr-tests/testthat/helper.R:177:2
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-error.R:11:3'): error is propagated, printed if non-interactive mode ──
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'asciicast'
Backtrace:
    ▆
 1. ├─callr:::expect_r_process_snapshot(...) at test-error.R:11:2
 2. └─base::loadNamespace(x) at callr-tests/testthat/helper.R:177:2
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-error.R:19:3'): error stack is passed, .Last.error is set ──────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'asciicast'
Backtrace:
    ▆
 1. ├─callr:::expect_r_process_snapshot(...) at test-error.R:19:2
 2. └─base::loadNamespace(x) at callr-tests/testthat/helper.R:177:2
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-error.R:80:3'): error traces are printed recursively ───────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'asciicast'
Backtrace:
    ▆
 1. ├─callr:::expect_r_process_snapshot(...) at test-error.R:80:2
 2. └─base::loadNamespace(x) at callr-tests/testthat/helper.R:177:2
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-error.R:152:3'): new_callr_error, timeout ──────────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'asciicast'
Backtrace:
    ▆
 1. ├─callr:::expect_r_process_snapshot(...) at test-error.R:152:2
 2. └─base::loadNamespace(x) at callr-tests/testthat/helper.R:177:2
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-error.R:198:3'): format.call_status_error 2 ────────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'asciicast'
Backtrace:
    ▆
 1. ├─callr:::expect_r_process_snapshot(...) at test-error.R:198:2
 2. └─base::loadNamespace(x) at callr-tests/testthat/helper.R:177:2
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-error.R:211:3'): stdout/stderr is printed on error ─────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'asciicast'
Backtrace:
    ▆
 1. ├─callr:::expect_r_process_snapshot(...) at test-error.R:211:2
 2. └─base::loadNamespace(x) at callr-tests/testthat/helper.R:177:2
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-error.R:224:3'): stdout/stderr is printed on error 2 ───────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'asciicast'
Backtrace:
    ▆
 1. ├─callr:::expect_r_process_snapshot(...) at test-error.R:224:2
 2. └─base::loadNamespace(x) at callr-tests/testthat/helper.R:177:2
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-error.R:237:3'): stdout/stderr is printed on error 3 ───────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'asciicast'
Backtrace:
    ▆
 1. ├─callr:::expect_r_process_snapshot(...) at test-error.R:237:2
 2. └─base::loadNamespace(x) at callr-tests/testthat/helper.R:177:2
 3.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 4.     └─base (local) withOneRestart(expr, restarts[[1L]])
 5.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-load-client.R:17:3'): errors ───────────────────────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'mockery'
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-load-client.R:17:2
 2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3.     └─base (local) withOneRestart(expr, restarts[[1L]])
 4.       └─base (local) doWithOneRestart(return(expr), restart)
── Error ('test-load-client.R:29:3'): errors 2 ─────────────────────────────────
<packageNotFoundError/error/condition>
Error in `loadNamespace(x)`: there is no package called 'mockery'
Backtrace:
    ▆
 1. └─base::loadNamespace(x) at test-load-client.R:29:2
 2.   └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 3.     └─base (local) withOneRestart(expr, restarts[[1L]])
 4.       └─base (local) doWithOneRestart(return(expr), restart)

[ FAIL 11 | WARN 0 | SKIP 26 | PASS 261 ]
Error: Test failures
Execution halted
