
R version 4.4.3 (2025-02-28) -- "Trophy Case"
Copyright (C) 2025 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> message("TESTING: throw()...")
TESTING: throw()...
> 
> library("R.oo")
Loading required package: R.methodsS3
R.methodsS3 v1.8.2 (2022-06-13 22:00:14 UTC) successfully loaded. See ?R.methodsS3 for help.
R.oo v1.27.0 (2024-11-01 18:00:02 UTC) successfully loaded. See ?R.oo for help.

Attaching package: ‘R.oo’

The following object is masked from ‘package:R.methodsS3’:

    throw

The following objects are masked from ‘package:methods’:

    getClasses, getMethods

The following objects are masked from ‘package:base’:

    attach, detach, load, save

> 
> ## Generate an error
> ex <- tryCatch({
+   stop("An error")
+ }, error = function(ex) {
+   ex
+ })
> print(ex)
<simpleError in doTryCatch(return(expr), name, parentenv, handler): An error>
> 
> ## Re-throw the error
> ex2 <- tryCatch({
+   throw(ex)
+ }, error = function(ex) {
+   ex
+ })
> print(ex2)
<simpleError in doTryCatch(return(expr), name, parentenv, handler): An error>
> 
> stopifnot(identical(ex2, ex))
> 
> 
> ## Generate an Exception
> ex <- tryCatch({
+   throw("An error")
+ }, error = function(ex) {
+   ex
+ })
> print(ex)
[2025-05-06 10:09:08.780363] Exception: An error
> 
> ## Re-throw the Exception
> ex2 <- tryCatch({
+   throw(ex)
+ }, error = function(ex) {
+   ex
+ })
> print(ex2)
[2025-05-06 10:09:08.780363] Exception: An error
> 
> stopifnot(identical(ex2, ex))
> 
> 
> message("TESTING: throw()...DONE")
TESTING: throw()...DONE
> 
